FROM alpine

RUN apk add --no-cache curl bash

WORKDIR /scripts
COPY src/test/k6/all.js .
COPY scripts/wait-for-it.sh .
RUN chmod +x wait-for-it.sh

RUN wget https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz && \
    tar -xzf k6-v0.49.0-linux-amd64.tar.gz && \
    mv k6-v0.49.0-linux-amd64/k6 /usr/local/bin/k6

ENTRYPOINT ["./wait-for-it.sh", "app:8080", "--", "k6", "run", "all.js"]
