- name: Add SSH Key
  uses: webfactory/ssh-agent@v0.7.0
  with:
    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

- name: Sync files to VPS
  run: |
    rsync -az -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/APIQuotation

- name: SSH and restart containers
  run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
      cd /home/${{ secrets.SSH_USER }}/APIQuotation
      docker-compose down
      docker-compose up --build -d
    EOF
